# Generated by Django 4.2.7 on 2025-11-24 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('gratuito', 'Gratuito'), ('basico', 'Básico - $5/mes'), ('premium', 'Premium - $10/mes')], default='gratuito', max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(default='Peru', max_length=100)),
                ('universidad', models.CharField(blank=True, max_length=200)),
                ('carrera', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio_suscripcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_suscripcion', models.DateTimeField(blank=True, null=True)),
                ('suscripcion_activa', models.BooleanField(default=False)),
                ('consultas_disponibles', models.IntegerField(default=3)),
                ('consultas_usadas_mes', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
